//GRAPHIC MANAGER
#define WIDTH 1200
#define HEIGHT 800
#define TICK_RATE 0.0078125

#define GRAVITY 0.0981

//PLAYER
#define PLAYER_SIZE_X 32
#define PLAYER_SIZE_Y 64
#define PLAYER_VELOCITY_X 20
#define PLAYER_JUMP_HEIGHT 0.6

//PLATFORM
#define PLATFORM_WIDTH 192
#define PLATFORM_HEIGHT 48

//SKELETON
#define SKELETON_SIZE_X 45
#define SKELETON_SIZE_Y 50

//GOBLIN
#define GOBLIN_SIZE_X 45
#define GOBLIN_SIZE_Y 50

//PROJECTILES

//BOMB
#define BOMB_SIZE_X 30
#define BOMB_SIZE_Y 30

